### ISSUE TITLE
ncp-rsync configure non-root account

### ISSUE THREAD

**Issue by mitodeboa** [nextcloud/nextcloudpi#1124]
**Description**  
Add the possibility of using non-root account to rsync

**Example**  
Adding the parameter --rsync-path="sudo rsync" to rsync command and configure sudoers in destination server

**Comment by sunjam** [comment]
Aren't you able to define a particular user for ncp-rsync besides root?

**Comment by nachoparker** [comment]
you select the user by typing it in the first field. See the default suggestion: `user@ip:/path/to/sync`.

**Comment by mitodeboa** [comment]
Yes, it is possible to define the user but rsync cannot set attributes, acl, time,... even if the user has permissions on the destination directory

**Comment by mitodeboa** [comment]
@nachoparker. I have verified that when doing rsync with a non-root user, errors occur when applying the attributes of the file and I have verified that if I add the mentioned parameter, those errors do not occur. This is a constructive contribution is not a request for support or criticism

**Comment by nachoparker** [comment]
Yes, thanks for the heads up.

I am pretty sure that by using the user there should be no issues with permissions as long as the rest of the systems are well configured.

We would need to dig a bit deeper into those errors for your particular case, but definitely using `user@` should work since we are simply using `rsync` which uses system users on the remote end.
