### ISSUE TITLE
Ownyourbits Down

### ISSUE THREAD

**Issue by imk13** [nextcloud/nextcloudpi#1485]
**System information**

`nslookup www.ownyourbits.com`

```
;; Got SERVFAIL reply from 8.8.8.8, trying next server
Server:		1.1.1.1
Address:	1.1.1.1#53

** server can't find www.ownyourbits.com: SERVFAIL
```
<img width="1779" alt="Screenshot 2022-06-05 at 8 15 16 PM" src="https://user-images.githubusercontent.com/8343415/172056530-b2d2cb39-8a3e-4da3-8d1a-3f7b280e0e8e.png">

**Comment by ben569** [comment]
Can confirm. Is someone on the case?

**Comment by riff-79** [comment]
Can confirm still down.

**Comment by GNEUGNEUGNEU** [comment]
yup, down

**Comment by nightm4re94** [comment]
+1

**Comment by pilepalle** [comment]
down.
Does anyone know if ownyourbits.com stays down?
If so, where can I get the RPI and odroid images?

**Comment by theCalcaholic** [comment]
Ownyourbits is down, because there has been a misunderstanding with the hoster. I don't know if it will be restored.

However, nextcloudpi.com will be migrated to a new hosting solution as soon as I can get to it. Images have been regenerated and can now be found in the GH release artifacts: https://github.com/nextcloud/nextcloudpi/releases/tag/v1.47.2

**Comment by sunjam** [comment]
Documentation from the dead `docs.nextcloudpi.com` has migrated to the forum:

https://help.nextcloud.com/c/ncpdocs/178
