### ISSUE TITLE
Multiple errors on a clean docker inastall

### ISSUE THREAD

**Issue by Jannik44** [nextcloud/nextcloudpi#1703]
Hello, i have multiple errors just by installing the default docker container without code changes etc.
1. i get "invalid origin" on every single option in the ncp-web panel (i heard that this can happen because of the ssl certificates, when using something different than default 443 on the host machine)
2. i get on a clean docker container these errors: (image)
![grafik](https://user-images.githubusercontent.com/76906033/212546456-221569f8-1e7f-4fdc-b19b-40fe3f72294d.png)
3. force https should be optional, not enabled by default because as mentioned it breaks the ncp admin panel

**Comment by ZendaiOwl** [comment]
The errors you are seeing are normal and is there for all fresh Nextcloud installations, even if I don't know German I recognize these errors. 

The first one is because the phone region has not been set in the config.php, this is not something we can do because we have no way of knowing what region a user is in. 

Nextcloud itself doesn't set this on purpose either, it's the same with the Raspberry Pi OS not setting the default WiFi country code because they have no way of knowing what country you are setting it up in, neither do we know what default phone region is correct for you.

https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#default-parameters

https://help.nextcloud.com/t/where-to-specify-default-phone-region-parameter/130475

It can be set using the `ncc` or `occ` command, or directly entered by editing the `config.php` file. 

Here's an example using the `ncc` command

`docker exec -it nextcloudpi ncc config:system:set default_phone_region --value="NL"`

You need to change `NL` to your own country code. 

The second error is due to `imagick` not being installed, which is a deliberate decision by default because of security concerns. I replied to another post regarding this on the forum [here](https://help.nextcloud.com/t/ncp-1-50-3-missing-imagick/147409/2?u=zendaiowl) 

The discussion from Nextcloud server devs about the security implications can be found [here](https://github.com/nextcloud/server/issues/13099), this discussion is also linked to in the forum post. 

You should still be able to access the admin panel even with force-https on, I just pulled and launched the v1.50.5 docker image and can access it just fine with the setting turned on?
