### ISSUE TITLE
Upgrade path beyond Nextcloud version 27.0.1 ?

### ISSUE THREAD

**Issue by Knubbel** [nextcloud/nextcloudpi#1838]
Currently NCP seems to be at 1.52.4 and only support a newest release of Nextcloud 27.0.1.

It would be great to know if / how / when there could be an upgrade path to newer Nextcloud releases.

As it is done by very nice volunteers I am happy to wait. Just give some perspective please.

**Comment by christoph-bittmann** [comment]
You could just run "nc-update-nextcloud" (see https://help.nextcloud.com/t/staying-up-to-date/126259) and type in the current nextcloud version (see here: https://nextcloud.com/de/changelog/) to update to the current nextcloud version. After successfully update, I recommend running the command again an type in "0" to stay up to date if nextcloudpi itself is updated.

**Comment by theCalcaholic** [comment]
I'm currently working on support for NC 27.1.3 (there are a few issues in my build system that I need to solve first). But, yes,  you can upgrade manually by entering the exact version without much worries, as @christoph-bittmann  stated.

**Comment by christoph-bittmann** [comment]
"I really want to stay on the safe side."

Sure, stability is important, but security for an server that's reachable from the internet is much more important. Nexctcloud pachtes fixes also security issues and should applied as soon as possible for each nexcloud instance. 
In my experience, the risk  to damage your system is very low when patching minor changes (27.x.x to 27.x.x). To be sure the nextcloud update will do an backup before executing the patch, but you could also do it by your own to be sure to have an "plan b" if anything goes wrong ...

For these why I would be happy to see much more often a new nextcloudpi version, at least every month on the regularly nextcloud patch day. Each patch could tested before on beta and/or release candidate channel.

**Comment by theCalcaholic** [comment]
The reason why upgrades currently take so long are mostly related to some issues with the build system that should be fixed with the next release. @NickKopernikus That's also the reason why there are no images available for some of the previous releases.

@Knubbel Yes, only NC versions up to a specific point are tested and enabled for auto updates. However, you can always install any release version of NC at the risk of breaking something. In this particular case, I have already tested v.27.1.2, so I know that it's fine to update to it without any changes to NCP. I just haven't gotten around to completing the release because of the aforementioned issues.

@christoph-bittmann An NCP beta (canary) channel will be part of the next two releases, as well as other changes that improve the upgrade process.

**Comment by theCalcaholic** [comment]
As NC 27.1.3 is currently supported (and support for 27.1.5 will be added in the next days), I'll close this ticket.

**Comment by theCalcaholic** [comment]
@Knubbel Auto upgrades are using the value configured in the manual upgrade button. But I suppose you are referring to manually upgrading to the latest available version (and selecting this version automatically). And for this case, what you describe is true - however this is unfortunately not changeable with the current ncp admin interface architecture (which will be rewritten mid-term)

**Comment by BurnSkat** [comment]
For general information,

I sucessfully upgraded my instance up to 28.0.3 using the updater script with no issue at all. I´m currently using NCP version 1.53.1 but i manually upgraded my php version to 8.1 beforehand using parts of this tutorial:
[https://www.c-rieger.de/upgrade-nextcloud/](url)

Overall performance is great on a Pi 4 and has improved with the update in my opinion. All apps are working fine.
Not to say that the update is totally save but it worked for me, so do it at your own risk and backup your data first.
