### ISSUE TITLE
HDD spin down?

### ISSUE THREAD

**Issue by testbird** [nextcloud/nextcloudpi#235]
I noticed that the HDD is always spinning. Is it not possible to save energy on low usage devices?

Maybe this a FAQ?
Found there were issues posted for database errors when the drive was in sleep.

**Comment by nachoparker** [comment]
[This user](https://help.nextcloud.com/t/solved-nextcloudpi-format-hdd-3tb/21362)  reported that and he reportedly fixed it with some ext4 parameters. I haven't tested this myself because I do not have that problem, but those parameters are now included in `nc-format-USB`.

Let us know if you investigate more.

Please, use the [forums](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm) for general questions like this.
