### ISSUE TITLE
can nextcloud pi be updated through the ui?

### ISSUE THREAD

**Issue by JunkyardCat** [nextcloud/nextcloudpi#26]
or is it still broken?

**Comment by nachoparker** [comment]
It can, only that in some cases it has been found to fail. This depends on many things, like your configuration or installed apps.

In order to minimize risks, it is recommended to backup your instance first with `nc-backup`.

See [here](https://ownyourbits.com/2017/05/24/nextcloudpi-gets-automount-backups-nextcloud-online-installation-nextcloud-12-and-more/) for more info on `nc-backup` and `nc-restore`

**Comment by JunkyardCat** [comment]
whats a docker?

**Comment by nachoparker** [comment]
A docker container is a technology to *pack* software such as NextCloudPi. You can google it.

There will still be images just the same, it is just an alternative method for getting NextCloudPi. I will support both from now on.

Please, open a different topic for each question so other people can benefit from the answers ;)
