### ISSUE TITLE
Can't enable SSH

### ISSUE THREAD

**Issue by aleprovencio** [nextcloud/nextcloudpi#356]
When trying the method described [here](https://github.com/nextcloud/nextcloudpi/wiki/How-to-install-NextCloudPi-on-a-Raspberry-Pi) even though trying a new non-existent the system always returns with the error message "The user pi is using the default password. Refusing to activate SSH".

Sorry for not pasting the output of `sudo ncp-report` because I guess that should be done via ssh.

**Comment by ovpc** [comment]
You can run nc-report from ncp-web at https://nextcloudpi.local:4443

**Comment by nachoparker** [comment]
you first have to do

user: _pi_
password: _something different_

in order to change the default password, that is insecure.

Then, you can log in through user _pi_ with that password, or also you can create new users and passwords without problems

I am planning on simplifying this by disabling the _pi_ user when you use this tool

**Comment by ovpc** [comment]
Extra info
In order to enable SSH, the password for user pi can not remain set to the default              
             │ raspberry.                                                                             │              
             │ You HAVE to create a NEW password for pi if you want this program to enable SSH, it    │              
             │ will fail if you dont!                                                                 │              
             │ Note: Use normal AlphaNumeric, the only special characters allowed are .,@-_/  
Just using thread to save screenshots for doc/wiki
![ncp-config-ssh-select](https://user-images.githubusercontent.com/8775469/34931799-c403a9bc-f9d0-11e7-9eaf-30864cdf657c.png)
![ncp-config-ssh-extrs-instructions](https://user-images.githubusercontent.com/8775469/34931804-c831be48-f9d0-11e7-9809-87d557677733.png)
![ncp-config-ssh-config-new-passwd](https://user-images.githubusercontent.com/8775469/34931808-cb1eaf30-f9d0-11e7-9494-0d51bfdc3a16.png)
[PULL Modified SSH HERE](https://github.com/ovpc/nextcloudpi/blob/master/etc/nextcloudpi-config.d/SSH.sh)

**Comment by aleprovencio** [comment]
Just to let you know, i tried changing the user `pi` password but then I got the error message `The user ncp is using the default password`. So instead of `pi` I changed passwords for the `ncp` user and everything now works as expected.

**Comment by UkeFan** [comment]
For ODroid-Users: The only users name that works is "root"

**Comment by ovpc** [comment]
[FAQ preset passwords](https://github.com/nextcloud/nextcloudpi/wiki/FAQ#what-are-pre-set-userspasswords-on-nextcloudpi)
