### ISSUE TITLE
Can't install Apps

### ISSUE THREAD

**Issue by nhall123** [nextcloud/nextcloudpi#392]
Just set up my NextCloudPi server per the instructions on the wiki. Attempting to install apps, but I just keep getting a blank page with HTTP Error 500. From the logging page, this looks to be the issue:

Class 'OC\App\AppStore\Fetcher\Fetcher' not found at /var/www/nextcloud/lib/private/App/AppStore/Fetcher/CategoryFetcher.php#30

What's the fix?

**Comment by nachoparker** [comment]
never seen that before. Try searching/asking in the general forums

[forums](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm)

because it only happens to you it must not be something NCP specific

if anyone else is seeing this, please reopen with the steps to reproduce and output of `sudo ncp-report`
