### ISSUE TITLE
Attempt to move swapfile fails

### ISSUE THREAD

**Issue by deljones** [nextcloud/nextcloudpi#455]
Hi

I have made a brand new install of the latest NCP. Everything is ok however if I try to move the swapfile to my USB drive I get the following warning which I have not seen before witn other installs

Launching nc-swapfile
BTRFS doesn't support swapfiles. You can still use nc-zram
Done. Press any key...

I have been able to move my DB and ncdata to the USB drive without issues

As a side item has anyone had any probleme with the themeing? The folders change colour based on your choice in the theming app but th emenue bar never changes.. Thats for another day

Dj

**Comment by nachoparker** [comment]
Hi @deljones 

Unfortunatedly BTRFS doesn't support swapfiles. The reason you didn't see this before is because we moved from ext4 to BTRFS for the USB drive filesystem because of it's many improvements, such as snapshots and snapshot sync.

Unfortunatedly we cannot move the swapfile there, but to compensate it ( and because it is good for performance ) I added the zram feature, that should be more than enough to add more virtual RAM to your system.

Thanks for your feedback, as usual ;)
