### ISSUE TITLE
nextcloudpi.local doesn't work on Android 7.1

### ISSUE THREAD

**Issue by java-py-c-cpp-js** [nextcloud/nextcloudpi#561]
nextcloudpi.local as address doesn't work on Android 7.1, neither with Lineageos nor with stock rom without modifikation, neither in a browser(Firefox, Chrome etc.) nor in the official Nextcloud app. On Linux/Firefox it is working. 

This issue refers to https://github.com/nextcloud/android/issues/2816

**Comment by nachoparker** [comment]
Hi, 

This is an Android problem, because [it doesn't support mDNS](https://android.stackexchange.com/questions/49188/how-to-get-mdns-working-for-chrome-on-android).

There's nothing we can do about this. As it is explained in the wiki, you can try the .local address but if it doesn't work, then you are left with the IP address, or your domain name.

Thanks for your feedback
