### ISSUE TITLE
Service unavailable when opening new installation via IP address

### ISSUE THREAD

**Issue by TomTurnschuh** [nextcloud/nextcloudpi#660]
The following issue I am able to reproduce many times in different environments:

1. Install an ODROID NCP image on a SD card and insert the card into an ODROID device.
2. Start the device.
3. Some seconds after, open the corresponding IP address in an arbitrary browser.
The following error shows up:
```
Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
```
4. Only a forced reboot of the device does help

Remark: It seems that waiting for a longer time until opening the IP address is better.

**Comment by Peuqui** [comment]
Hi there,
after some issues getting the docker-image running on a Raspi 3 B+, I tried to complete reinstall a new clean one. But I can't get it to run: the webpage shows: "Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later." I added the docker-log output fyi.

[Docker-NextcloudPi-Log.txt](https://github.com/nextcloud/nextcloudpi/files/2437548/Docker-NextcloudPi-Log.txt)

**Comment by nachoparker** [comment]
@TomTurnschuh in your case, the system was probably booting up and PHP was probably caching. Doesn't seem like an issue

**Comment by TomTurnschuh** [comment]
> 
> 
> @TomTurnschuh in your case, the system was probably booting up and PHP was probably caching. Doesn't seem like an issue

That might be true. However, Peuqui's issue seems to be different, see the Telegram discussion.
