### ISSUE TITLE
Accessing nextcloud files from the raspberry pi

### ISSUE THREAD

**Issue by GustaveCoste** [nextcloud/nextcloudpi#77]
I would like to write and read to my nextcloud folder from other apps (deluge for downloading files to the folder and Kodi to read files from it). NextCloudPi autoscan features could help me to scan written files.
I thought I might do something with symbolic links and group permissions but I don't want to mess it all up.
Is there a clean way to do this?

**Comment by nachoparker** [comment]
Well, I am afraid that is the better way I can think of. Nextcloud files are owned by `www-data:www-data`, so unless you adjust the ownership of your downloads, Nextcloud will see them (after scan) but will not be able to modify/delete them. If you need  to modify them from NC you could add an 'after-download script' to adjust ownership (some programs allow this), or schedule a periodic process to do it.

The user that runs kodi also needs read access. It probably already has, otherwise you can add it to the `www-data` group.

Nothing very elegant I am afraid. Ideas welcome
