### ISSUE TITLE
odroid HDD 'clack noise' parking  fix from Odroid 

### ISSUE THREAD

**Issue by GreyMarvel** [nextcloud/nextcloudpi#774]
Hi all,
I'm not sure if this is useful or not but I stumbled across this on odroid's website. It's a workaround fix, for the hardrive parking 'clack noise ' on shutdown and I believe on the forum there is a workaround script for a reboot as well . 
I haven't run the the scripts myself as I'm not really an expert and would prefer a more experienced person check it first .

https://wiki.odroid.com/odroid-xu4/troubleshooting/shutdown_script

https://forum.odroid.com/viewtopic.php?f=97&t=29069&p=214073#p215794

**Comment by nachoparker** [comment]
wow thank you

**Comment by zedocrob** [comment]
i use this script since a few month without issue on Odroid HC2, no "clack noise" on shutdown.
But i also had to set the firmware spindown timing to "never" like that:
`root@odroid:~# ./JMS578FwUpdate -d /dev/sda -f ./JMS578_Hardkernel_v173.01.00.01.bin -b ./backup.bin -t 0`
Mean reflashing the firmware with:` -t 0` (no spindown)
Otherwise the firmware is set to 3min before spindown by default wich was causing high Power-Off_Retract_Count!

Then check if the shutdown script is still there (or reapply it).

check this thread about the firmware 3min default spindown problem!:
https://forum.odroid.com/viewtopic.php?f=97&t=31985

**Comment by GreyMarvel** [comment]
Is this something that can be incorporated into a NextcloudPi update /image ?

**Comment by nachoparker** [comment]
It could, but it's low priority for me. It might happen if I receive a PR

**Comment by zedocrob** [comment]
That'll be cool
Also be careful with the firmware flashing, maybe detach the drive before...I've experienced a corruption after flashing the Odroid HC2 firmware, and after rebooting:
( ncdata input/output error... ). :(

**Comment by funkmastergst** [comment]
Not quite sure if this is helpful, but my WDred installed in ODroid HC2 since several months shows "192 Power-Off_Retract_Count 0x0032 200 200 000 Old_age Always - 0" in Check HDD health.

**Comment by nachoparker** [comment]
Assuming this fix has been included in the latest Armbian images. If it is not, then we should report it to the Armbian team.

**Comment by GreyMarvel** [comment]
It is now on the new images,  I remember seeing the updated files recently but forgot to close the issue.
Thanks nacho for your great work .
