### ISSUE TITLE
Cant Update Nextcloud

### ISSUE THREAD

**Issue by awkscp** [nextcloud/nextcloudpi#922]
On the web interface I cant update Nextcloudpi. After I click on update It shows a red dot and nothing happens. Also my version on the top left is set to 0.0.0.

I tried to update via ncp-config but it says 
file /usr/local/bin/ncp/TOOLS/nc-update.sh
/usr/local/bin/ncp/UPDATES/nc-update.sh not found

**Comment by ovpc** [comment]
This is really not the place to try and get help, please use the [forum](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm).

Try to provide information on your setup, versions of NC and NCP initially installed, installation method and image used. Include (pastebin or similar) links to logs; ncp.log and output of ncp-report. Let us know what you tried to do or checked to solve the problem. We need to be able to reproduce it, for it be considered a bug.
If it turns out to be a bug, anyone is free to re-open and respond here. Thank you
